
export const ACCOUNT_CHART = {
  POOL_BALANCE: "ASSET_POOL_BALANCE",
  MEMBER_CONTRIBUTION: "LIABILITY_MEMBER_CONTRIBUTION",
  MEMBER_WITHDRAWAL: "LIABILITY_MEMBER_WITHDRAWAL",
  SUSPENSE: "ASSET_SUSPENSE",
} as const;

export type AccountCode = (typeof ACCOUNT_CHART)[keyof typeof ACCOUNT_CHART];
